// playground/svelte/src/lib/Profiles.svelte
<script lang="ts">
  import { relay, user } from "@nostr-stack/core";
  import { onMount } from "svelte";

  const pool = new relay.RelayPool([
    "wss://eden.nostr.land",
    "wss://nostr.wine",
    "wss://nos.lol",
  ]);
  let profiles: user.UserProfile[] = [];
  let input = "";
  let buttonDisabled = false;
  $: nip05s = input.split(", ");
  $: displayProfiles = profiles.map((p) => user.toDisplayProfile(p));

  const getPubKeys = async () => {
    return (await (
      await Promise.all(nip05s.map((n) => user.getPublicKeyFromNip05(n)))
    ).filter((n) => !!n)) as string[];
  };

  const getProfiles = async () => {
    buttonDisabled = true;
    const pubKeys = await getPubKeys();
    const profiles = await user.getProfiles(pubKeys, pool);
    buttonDisabled = false;
    return profiles;
  };
</script>

<div>
  <form on:submit|preventDefault={async () => (profiles = await getProfiles())}>
    <label
      >Enter a Nip05 addresses
      <input type="text" bind:value={input} />
    </label>
    <button disabled={buttonDisabled}>Search</button>
  </form>
  <div class="profiles">
    {#each displayProfiles as profile}
      <p>Public key is {profile.pubkey}</p>
      <p>Name is {profile.name}</p>
      <p>Display name is {profile.display_name}</p>
      <p>
        Your picture looks like this <img src={profile.picture} alt="profile" />
      </p>
    {/each}
  </div>
</div>

<style>
  img {
    border-radius: 100%;
    height: 100px;
    width: 100px;
  }
  .profiles {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
</style>

// playground/react/src/Profiles.tsx
import { useProfiles } from "@nostr-stack/react";
import { user } from "@nostr-stack/core";
import { useEffect, useState } from "react";

export const Profiles = () => {
  const [nip05s, setNip05s] = useState<string[]>(["borrakkor@nostrplebs.com"]);
  const [pubkeys, setPubkeys] = useState<string[]>([]);

  const search = () => {
    Promise.all(nip05s.map((p) => user.getPublicKeyFromNip05(p))).then(
      (pks) => {
        const nonNull = pks.filter((p) => !!p && p !== "") as string[];
        setPubkeys(nonNull);
      }
    );
  };

  const profiles = useProfiles(pubkeys, { cache: true, persist: true });
  return (
    <div>
      <div>
        <h4>Profiles</h4>
        <label>Nip05 Profiles</label>
        <textarea
          value={nip05s.join("\n")}
          style={{ width: 300 }}
          rows={10}
          onChange={(e) => setNip05s(e.target.value.split("\n"))}
        />
        <button onClick={search}>Search</button>
      </div>
      {profiles.map((p) => (
        <Profile userSettings={p} />
      ))}
    </div>
  );
};

const Profile = ({ userSettings }: { userSettings: user.UserProfile }) => {
  return (
    <div>
      <h4>Pubkey is {userSettings.pubkey}</h4>
      <h4>Name is {userSettings.name}</h4>
      <h4>{userSettings.about}</h4>
      {userSettings.picture && <img src={userSettings.picture} />}
    </div>
  );
};
